name: Terveystarkistus

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 13 * * *'

jobs:
  tarkista_toimivuus:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://sleepy-temple-41588.herokuapp.com/health
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "no"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "no"
      - name: say hello to Henzi
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Terveystarkistus suoritettu.